server:
    port: 8088 # 配置服务端口号
#    servlet:
#        context-path: /ruosen  # 配置服务上下文
spring:
    profiles:
        active: dev  # 启用dev配置文件
    datasource:  # 数据源配置
        url: jdbc:mysql://127.0.0.1:3306/ruosen-star?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        druid:
            stat-view-servlet:
                enabled: true
    # redis相关配置
    redis:
        host: 127.0.0.1
        port: 6379
        database: 1
    # rabbitMq 配置
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: ruosen-star
        password: 123456
        virtual-host: /ruosen-star
        publisher-confirms: true
    # quartz 配置
    quartz:
        job-store-type: jdbc
        jdbc:
            initialize-schema: never
        scheduler-name: RuosenStarScheduler
        properties:
            org:
                quartz:
                    jobStore:
                        tablePrefix: QRTZ_
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        isClustered: true
# mybatis-plus 配置
mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
    type-aliases-package: com.ruosen.star.ruosenstar.module.po  #实体扫描，多个package用逗号或者分号分隔
    global-config:
        db-column-underline: true
        id-type: 0
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false

app:
    mq:
        topic-exchange: ruosen-start.topic
        registerQueue:
            bindingTopicExchangePushQueue:
                queueName: PUSH_TEST_MQ
                queueBeanName: pushTestMq
                routingKey: test.rabbit
            bindingTopicExchangeReplyQueue:
                queueName: REPLY_TEST_MQ
                queueBeanName: ReplyhTestMq
                routingKey: test.rabbit