server:
    port: 8088 # 配置服务端口号
#    servlet:
#        context-path: /ruosen  # 配置服务上下文
spring:
    profiles:
        active: dev  # 启用dev配置文件
    datasource:  # 数据源配置
        url: jdbc:mysql://127.0.0.1:3306/ruosen-star?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        druid:
            stat-view-servlet:
                enabled: true
    # redis相关配置
    redis:
        host: 127.0.0.1
        port: 6379
        database: 1
    # rabbitMq 配置
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: ruosen
        password: ruosen
        virtual-host: /ruosen
        publisher-confirms: true
    # quartz 配置
    quartz:
        job-store-type: jdbc
        jdbc:
            initialize-schema: never
        scheduler-name: RuosenStarScheduler
        properties:
            org:
                quartz:
                    jobStore:
                        tablePrefix: QRTZ_
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        isClustered: true
    mail:
        host: smtp.163.com
        username: 18687269789@163.com
        password:
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
#    freemarker:
#        content-type: text/html
#        #后缀名
#        suffix: .html
#        template-loader-path: classpath:/templates
#        charset: UTF-8
#        check-template-location: true

    thymeleaf:
        cache: false # mybatis-plus 配置
        check-template: true
        encoding: UTF-8
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
    global-config:
        db-config:
            id-type: auto
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
    type-aliases-package: com.ruosen.star.ruosenstar.module.po


app:
    mq:
        topic-exchange: ruosen-start.topic
        registerQueue:
            bindingTopicExchangePushQueue:
                queueName: PUSH_TEST_MQ
                queueBeanName: pushTestMq
                routingKey: test.rabbit
            bindingTopicExchangeReplyQueue:
                queueName: REPLY_TEST_MQ
                queueBeanName: ReplyhTestMq
                routingKey: test.rabbit

#设置一个邮件发送人
lance:
    mail:
        sender: 18687269789@163.com

# 微信支付相关配置
wechat:
    appId: wx632c8f211f8122c6   # 微信公众号的 id
    mchId: 1497984412   # 商户 id
    apiKey: sbNCm1JnevqI36LrEaxFwcaT0hkGxFnC  # 密钥
    ufdooerUrl: https://api.mch.weixin.qq.com/pay/unifiedorder  # 微信的统一下单地址
    notifyUrl: http://pic.chenjunbo.xin/payment/result # 回调 URL
    createIp: 180.130.10.113  # 发起 IP

